version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
