    name: Detect Push on Main

    #Déclencheur pour les événements "push" sur la branche "main"
    on:
      push:
        branches:
          - master

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          # Étape 1 : Vérification du code source
          - name: Checkout code
            uses: actions/checkout@v3

          # Étape 2 : Afficher un message
          - name: Print a message
            run: echo "A push has been detected on the main branch!"

          # Étape 3 : Mettre à jour les paquets et installer OpenSSH
          - name: Update packages and install OpenSSH
            run: |
              sudo apt-get update && sudo apt-get upgrade -y
              sudo apt-get install -y openssh-client

         # Étape 4 : Ajout de la clé privée pour la connexion SSH
          - name: Setup SSH Key
            env:
              PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            run: |
              mkdir -p ~/.ssh
              echo "$PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa

          # Étape 4 : Se connecter via SSH et effectuer les commandes
          - name: SSH and deploy
            env:
              HOST: ${{ secrets.SSH_HOST }}
              USER: ${{ secrets.SSH_USER }}
              WORK_DIR: ${{ secrets.WORK_DIR }}
            run: |
              ssh -o StrictHostKeyChecking=no admin@16.170.202.113 << EOF
                cd /home/admin/www/test-react-soudry
                git pull
              EOF
