    name: Detect Push on Main

    #Déclencheur pour les événements "push" sur la branche "main"
    on:
      push:
        branches:
          - master

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          # Étape 1 : Vérification du code source
          - name: Checkout code
            uses: actions/checkout@v3

          # Étape 2 : Afficher un message
          - name: Print a message
            run: echo "A push has been detected on the main branch!"

          # Étape 3 : Mettre à jour les paquets et installer OpenSSH
          - name: Update packages and install OpenSSH
            run: |
              sudo apt-get update && sudo apt-get upgrade -y
              sudo apt-get install -y openssh-client

          # Étape 4 : Se connecter via SSH et effectuer les commandes
          - name: SSH and deploy
            env:
              HOST: ${{ secrets.SSH_HOST }}
              USER: ${{ secrets.SSH_USER }}
              WORK_DIR: ${{ secrets.WORK_DIR }}
            run: |
              ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
                cd $WORK_DIR
                git pull
              EOF
